FROM cgr.dev/chainguard-private/jdk:openjdk-8.412-dev
USER root
RUN apk add maven
USER java
RUN git clone https://github.com/openjdk/jmh
COPY JMHSample_40_max.java /home/build/jmh/jmh-samples/src/main/java/org/openjdk/jmh/samples/
RUN cd jmh && mvn clean verify || true
ENTRYPOINT bash

# cd jmh-samples
# java -jar target/benchmarks.jar JMHSample_40